CREATE SCHEMA IF NOT EXISTS pubs DEFAULT CHARACTER SET utf8;
USE pubs;

CREATE TABLE IF NOT EXISTS LOCALIDAD (
    COD_LOCALIDAD INT NOT NULL,
    locNombre VARCHAR(30) NOT NULL,
    PRIMARY KEY (COD_LOCALIDAD)
);

CREATE TABLE IF NOT EXISTS PUB (
    codPub VARCHAR(30) NOT NULL,
    pubNombre VARCHAR(30) NOT NULL,
    licenciaFiscal VARCHAR(30) NOT NULL,
    domicilioPub VARCHAR(30) NULL,
    horario ENUM('H1', 'H2', 'H3') NOT NULL,
    COD_LOCALIDAD INT NOT NULL,
    PRIMARY KEY (codPub),
    FOREIGN KEY (COD_LOCALIDAD) REFERENCES LOCALIDAD(COD_LOCALIDAD) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TITULAR (
    DNI_TITULAR VARCHAR(9) NOT NULL,
    titNombre VARCHAR(30) NOT NULL,
    domiciliotit VARCHAR(30) NULL,
    codPubFK1 VARCHAR(30) NOT NULL,
    PRIMARY KEY (DNI_TITULAR),
    FOREIGN KEY (codPubFK1) REFERENCES PUB(codPub) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EMPLEADO (
    DNI_EMPLEADO VARCHAR(9) NOT NULL,
    empNombre VARCHAR(30) NOT NULL,
    domicilioemp VARCHAR(30) NULL,
    PRIMARY KEY (DNI_EMPLEADO)
);

CREATE TABLE IF NOT EXISTS EXISTENCIAS (
    COD_ARTICULO VARCHAR(30) NOT NULL,
    exsNombre VARCHAR(30) NOT NULL,
    cantidad INT NOT NULL,
    precio FLOAT NOT NULL,
    cod_PubFK2 VARCHAR(30) NOT NULL,
    PRIMARY KEY (COD_ARTICULO),
    FOREIGN KEY (cod_PubFK2) REFERENCES PUB(codPub) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PUB_EMPLEADO (
    COD_PUBNM VARCHAR(30) NOT NULL,
    DNI_EMPLEADONM VARCHAR(9) NOT NULL,
    FUNCION VARCHAR(30) NOT NULL,
    PRIMARY KEY (COD_PUBNM, DNI_EMPLEADONM, FUNCION),
    FOREIGN KEY (COD_PUBNM) REFERENCES PUB(codPub) ON DELETE CASCADE,
    FOREIGN KEY (DNI_EMPLEADONM) REFERENCES EMPLEADO(DNI_EMPLEADO) ON DELETE CASCADE
);

INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO1, APELLIDO2, SEXO) VALUES
(111222, 'Sergio', 'Palma', 'Entrena', 'H'),
(222333, 'Lucia', 'Ortega', 'Plus', 'M');

INSERT INTO HISTORIAL_LABORAL (EMPLEADO_DNI, TRABAJO_COD, FECHA_INICIO, FECHA_FIN, DPTO_COD, SUPERVISOR_DNI) VALUES
(111222, NULL, '1996-06-16', NULL, 222333, NULL);