CREATE SCHEMA IF NOT EXISTS empleados_estudios DEFAULT CHARACTER SET utf8;
USE empleados_estudios;

CREATE TABLE IF NOT EXISTS EMPLEADOS (
    DNI INT(8) NOT NULL,
    NOMBRE VARCHAR(10) NOT NULL,
    APELLIDO1 VARCHAR(15) NOT NULL,
    APELLIDO2 VARCHAR(15),
    DIREC1 VARCHAR(25),
    DIREC2 VARCHAR(20),
    CIUDAD VARCHAR(20),
    PROVINCIA VARCHAR(20),
    COD_POSTAL VARCHAR(5),
    SEXO ENUM('H', 'M') NOT NULL,
    FECHA_NAC DATE,
    PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTOS (
    DPTO_COD INT(5) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL UNIQUE,
    DPTO_PADRE INT(5),
    PRESUPUESTO INT NOT NULL,
    PRES_ACTUAL INT,
    PRIMARY KEY (DPTO_COD)
);

CREATE TABLE IF NOT EXISTS UNIVERSIDADES (
    UNIV_COD INT(5) NOT NULL,
    NOMBRE VARCHAR(25) NOT NULL,
    CIUDAD VARCHAR(20),
    MUNICIPIO VARCHAR(2),
    COD_POSTAL VARCHAR(5),
    PRIMARY KEY (UNIV_COD)
);

CREATE TABLE IF NOT EXISTS ESTUDIOS (
    EMPLEADO_DNI INT(8) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    UNIVERSIDAD INT(5),
    ANIO INT(4),
    GRADO VARCHAR(3),
    ESPECIALIDAD VARCHAR(20),
    PRIMARY KEY (EMPLEADO_DNI, NOMBRE)
);

CREATE TABLE IF NOT EXISTS HISTORIAL_SALARIAL (
    EMPLEADO_DNI INT(8) NOT NULL,
    FECHA_COMIENZO DATE NOT NULL,
    SALARIO INT NOT NULL,
    FECHA_FIN DATE,
    PRIMARY KEY (EMPLEADO_DNI, FECHA_COMIENZO)
);

CREATE TABLE IF NOT EXISTS TRABAJOS (
    TRABAJO_COD INT(5) NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL UNIQUE,
    SALARIO_MIN INT NOT NULL,
    SALARIO_MAX INT NOT NULL,
    PRIMARY KEY (TRABAJO_COD)
);

CREATE TABLE IF NOT EXISTS HISTORIAL_LABORAL (
    EMPLEADO_DNI INT(8) NOT NULL,
    TRABAJO_COD INT(5) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE,
    DPTO_COD INT(5),
    SUPERVISOR_DNI INT(8),
    PRIMARY KEY (EMPLEADO_DNI, FECHA_INICIO)
);

ALTER TABLE DEPARTAMENTOS 
ADD CONSTRAINT FK_DPTO_PADRE FOREIGN KEY (DPTO_PADRE) REFERENCES DEPARTAMENTOS(DPTO_COD);

ALTER TABLE ESTUDIOS 
ADD CONSTRAINT FK_ESTUDIOS_EMPLEADO FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI),
ADD CONSTRAINT FK_ESTUDIOS_UNIVERSIDAD FOREIGN KEY (UNIVERSIDAD) REFERENCES UNIVERSIDADES(UNIV_COD);

ALTER TABLE HISTORIAL_SALARIAL 
ADD CONSTRAINT FK_HISTORIAL_SALARIAL_EMPLEADO FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI);

ALTER TABLE HISTORIAL_LABORAL 
ADD CONSTRAINT FK_HISTORIAL_LABORAL_EMPLEADO FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI),
ADD CONSTRAINT FK_HISTORIAL_LABORAL_TRABAJO FOREIGN KEY (TRABAJO_COD) REFERENCES TRABAJOS(TRABAJO_COD),
ADD CONSTRAINT FK_HISTORIAL_LABORAL_DPTO FOREIGN KEY (DPTO_COD) REFERENCES DEPARTAMENTOS(DPTO_COD) ON DELETE SET NULL,
ADD CONSTRAINT FK_HISTORIAL_LABORAL_SUPERVISOR FOREIGN KEY (SUPERVISOR_DNI) REFERENCES EMPLEADOS(DNI);

-- Insertar datoss
INSERT INTO EMPLEADOS (DNI, NOMBRE, APELLIDO1, APELLIDO2, SEXO) VALUES
(111222, 'Sergio', 'Palma', 'Entrena', 'H'),
(222333, 'Lucia', 'Ortega', 'Plus', 'M');

INSERT INTO TRABAJOS (TRABAJO_COD, NOMBRE, SALARIO_MIN, SALARIO_MAX) VALUES
(1001, 'Ingeniero', 2000, 5000);

INSERT INTO DEPARTAMENTOS (DPTO_COD, NOMBRE, PRESUPUESTO) VALUES
(222333, 'Recursos Humanos', 500000);

INSERT INTO HISTORIAL_LABORAL (EMPLEADO_DNI, TRABAJO_COD, FECHA_INICIO, FECHA_FIN, DPTO_COD, SUPERVISOR_DNI) VALUES
(111222, 1001, '1996-06-16', NULL, 222333, NULL);
