CREATE SCHEMA IF NOT EXISTS proyectos;
USE proyectos;

CREATE TABLE IF NOT EXISTS EMPLEADOS (
	DNI VARCHAR(9) NOT NULL,
    Nombre VARCHAR(25) NOT NULL,
    Apellido VARCHAR(25) NOT NULL,
    Cargo ENUM('Director','Junior','Senior','Gestor','Responsable') NOT NULL,
    PRIMARY KEY (DNI)
);

CREATE TABLE IF NOT EXISTS CLIENTES (
	CIF VARCHAR(9) NOT NULL,
    NombreEmpresa VARCHAR(30) UNIQUE NOT NULL,
    ContactoNombre VARCHAR(25) NOT NULL,
    TLF INT NOT NULL,
    Municipio INT NOT NULL,
    PRIMARY KEY (CIF)
);


CREATE TABLE IF NOT EXISTS PROYECTOS (
	ProyectoID INT NOT NULL,
	NombreProyecto VARCHAR(30) NOT NULL UNIQUE,
	FechaInicio DATETIME NOT NULL,
	FechaEntrega DATETIME NOT NULL,
	ClienteID VARCHAR(9) NOT NULL, -- FK Cliente
	ResponsableID VARCHAR(9), -- FK_empleado
	Presupuesto INT NOT NULL,
    PRIMARY KEY (ProyectoID),
    FOREIGN KEY (ClienteID) REFERENCES CLIENTES(CIF) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ResponsableID) REFERENCES EMPLEADOS(DNI) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS TAREAS(
	TareaID INT NOT NULL,
	ProyectoID INT NOT NULL, -- FK_Proyectos
	FechaAsignacion DATETIME NOT NULL,
	FechaLimite DATETIME NOT NULL,
	Descripcion VARCHAR(100),
    PRIMARY KEY (TareaID),
    FOREIGN KEY (ProyectoID) REFERENCES PROYECTOS(ProyectoID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS AVANCES_TAREAS (
	TareaID INT NOT NULL, -- FK_Tareas
	ProyectoID INT NOT NULL, -- FK_Tareas
	PorcentajeAvance INT NOT NULL DEFAULT 0, -- POR DEFECTO 0
    PRIMARY KEY (TareaID, ProyectoID),
    FOREIGN KEY (TareaID) REFERENCES TAREAS(TareaID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ProyectoID) REFERENCES TAREAS(ProyectoID) ON DELETE CASCADE ON UPDATE CASCADE
);