-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 13:25:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema starwars
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema starwars
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `starwars` DEFAULT CHARACTER SET utf8 ;
USE `starwars` ;

-- -----------------------------------------------------
-- Table `starwars`.`Trooper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starwars`.`Trooper` (
  `codigo` INT NOT NULL,
  `categoriaT` VARCHAR(45) NOT NULL,
  `es_clon` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starwars`.`Planeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starwars`.`Planeta` (
  `nombreP` VARCHAR(20) NOT NULL,
  `galaxia` VARCHAR(20) NOT NULL,
  `cantidadHabitantes` INT NOT NULL,
  PRIMARY KEY (`nombreP`, `galaxia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starwars`.`SITH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starwars`.`SITH` (
  `nombreS` VARCHAR(20) NOT NULL,
  `tieneAprendiz` TINYINT NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `codigoT` INT NOT NULL,
  `nombreP` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`nombreS`),
  INDEX `trooper_sith_idx` (`codigoT` ASC) VISIBLE,
  INDEX `sith_planeta_idx` (`nombreP` ASC) VISIBLE,
  CONSTRAINT `trooper_sith`
    FOREIGN KEY (`codigoT`)
    REFERENCES `starwars`.`Trooper` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sith_planeta`
    FOREIGN KEY (`nombreP`)
    REFERENCES `starwars`.`Planeta` (`nombreP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starwars`.`SABLE LASER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starwars`.`SABLE LASER` (
  `categoriaSL` VARCHAR(45) NOT NULL,
  `colorSL` SET('plata', 'oro', 'cromo', 'negro', 'blanco') NOT NULL,
  `componente` INT NOT NULL,
  `tipoCristal` CHAR(1) NOT NULL,
  PRIMARY KEY (`categoriaSL`, `tipoCristal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starwars`.`JEDI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starwars`.`JEDI` (
  `nombreJ` VARCHAR(20) NOT NULL,
  `nivelAprendizaje` SET('A', 'B', 'C', 'D', 'E') NOT NULL,
  `nivelEnergía` INT(100) NOT NULL,
  `reemplaza` VARCHAR(45) NOT NULL,
  `categoriaSL` INT NOT NULL,
  PRIMARY KEY (`nombreJ`),
  INDEX `sable_jedi_idx` (`categoriaSL` ASC) VISIBLE,
  CONSTRAINT `replaces`
    FOREIGN KEY ()
    REFERENCES `starwars`.`JEDI` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sable_jedi`
    FOREIGN KEY (`categoriaSL`)
    REFERENCES `starwars`.`SABLE LASER` (`categoriaSL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starwars`.`Nave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starwars`.`Nave` (
  `tipoN` INT NOT NULL,
  `modelo` VARCHAR(7) NOT NULL,
  `nombreJ` VARCHAR(20) NOT NULL,
  `motor` TINYINT NOT NULL,
  `chasis` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`tipoN`, `modelo`, `nombreJ`),
  INDEX `nave_jedi_idx` (`nombreJ` ASC) VISIBLE,
  CONSTRAINT `nave_jedi`
    FOREIGN KEY (`nombreJ`)
    REFERENCES `starwars`.`JEDI` (`nombreJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starwars`.`tatuaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starwars`.`tatuaje` (
  `nombreS` VARCHAR(45) NOT NULL,
  `lugar` VARCHAR(45) NOT NULL,
  `color` SET('rojo', 'azul', 'verde') NOT NULL,
  PRIMARY KEY (`nombreS`),
  CONSTRAINT `sith_tatuaje`
    FOREIGN KEY (`nombreS`)
    REFERENCES `starwars`.`SITH` (`nombreS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starwars`.`Androide`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starwars`.`Androide` (
  `numSerie` INT NOT NULL,
  `codFrabricacion` VARCHAR(10) NOT NULL,
  `apodo` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  `nombreJ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numSerie`, `codFrabricacion`),
  INDEX `jedi_androide_idx` (`nombreJ` ASC) VISIBLE,
  CONSTRAINT `jedi_androide`
    FOREIGN KEY (`nombreJ`)
    REFERENCES `starwars`.`JEDI` (`nombreJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starwars`.`PELEA CON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starwars`.`PELEA CON` (
  `nombreJ` VARCHAR(20) NOT NULL,
  `nombreS` VARCHAR(20) NOT NULL,
  `fecha` DATE NOT NULL,
  `region` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombreJ`, `nombreS`),
  INDEX `sith_pc_idx` (`nombreS` ASC) VISIBLE,
  CONSTRAINT `jedi_pc`
    FOREIGN KEY (`nombreJ`)
    REFERENCES `starwars`.`JEDI` (`nombreJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sith_pc`
    FOREIGN KEY (`nombreS`)
    REFERENCES `starwars`.`SITH` (`nombreS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starwars`.`Armamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starwars`.`Armamento` (
  `codigoT` INT NOT NULL,
  `armamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigoT`),
  CONSTRAINT `armamento_trooper`
    FOREIGN KEY (`codigoT`)
    REFERENCES `starwars`.`Trooper` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starwars`.`Poder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starwars`.`Poder` (
  `nombreS` VARCHAR(20) NOT NULL,
  `poder` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombreS`),
  CONSTRAINT `poder_sith`
    FOREIGN KEY (`nombreS`)
    REFERENCES `starwars`.`SITH` (`nombreS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starwars`.`Habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starwars`.`Habilidad` (
  `nombreJ` VARCHAR(20) NOT NULL,
  `habilidad` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`nombreJ`),
  CONSTRAINT `habilidad_jedi`
    FOREIGN KEY (`nombreJ`)
    REFERENCES `starwars`.`JEDI` (`nombreJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `starwars`.`Componente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starwars`.`Componente` (
  `categoriaSL` VARCHAR(45) NOT NULL,
  `componente` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`categoriaSL`),
  CONSTRAINT `componente_sable`
    FOREIGN KEY (`categoriaSL`)
    REFERENCES `starwars`.`SABLE LASER` (`categoriaSL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
